name: Size delta PR

on:
  workflow_run:
    workflows: [ "Compile examples" ]
    types: [ completed ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@v1
        with:
          # The name of the workflow artifact created by the "Compile Examples" workflow
          sketches-reports-source: sketches-reports
