name: Spell check

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spell check
        uses: codespell-project/actions-codespell@v2
        with:
          skip: ./doc/Doxygen/**,./doc/Doxygen/*
